services:
    innomatic.config.resolver.chain:
        class: Innomatic\Bundle\InnomaticCoreBundle\DependencyInjection\Configuration\ChainConfigResolver

    innomatic.config.resolver:
        alias: innomatic.config.resolver.chain

    innomatic.chain_router:
        class: Innomatic\Core\MVC\Symfony\Routing\ChainRouter
        arguments: [@?logger]
        calls:
            - [setContext, [@router.request_context]]